### ISSUE TITLE
README.md/Windows 10: %cd% construction not valid on Windows 10

### ISSUE THREAD

**Issue by mwherman2000** [kdenhartog/indy-dev#12]
All of the following steps appear to have executed properly *except* for the last one.  The `%cd%` construction isn't recognized in Windows 10.  Given that I cloned the repo into `c:\INDY\indy-dev`, what should I be specifying for the last command line?
```
c:
mkdir c:\INDY
git clone https://github.com/kdenhartog/indy-dev.git
cd    c:\INDY\indy-dev
docker build -f indy-pool.dockerfile -t indy_pool .
docker build -f indy-dev.dockerfile -t indy_dev .
docker run -itd --net=host -p 127.0.0.1:9701-9708:9701-9708 indy_pool
docker run -it --net=host -p 127.0.0.1:8080:8080 -v %cd%:/home/indy indy_dev
```

**Comment by kdenhartog** [comment]
Are you executing this through the linux subsystem on windows 10 or are you using CMD for your shell?

**Comment by kdenhartog** [comment]
I'm not familiar with Java containers. Essentially what the `%cd%:/home/indy` is telling docker to do is take the current directory (using Window's commands) and mount that to the directory `/home/indy` inside the container. So, the only change to the command should be to figure out what is the command to specify the current directory. 

Alternatively, docker allows you to specify a specific path. You could replace the `%cd%` part with the location of the repository on your local filesystem and it will be able to mount it directly.

**Comment by mwherman2000** [comment]
Kyle, I mispoke.  I changed the sentence to  I'm using _Linux_ containers and not Windows containers. ...but it looks like you beat to it.  I'm using Linux containers on native Windows 10 Docker Desktop ...no Linux subsystem.

**Comment by mwherman2000** [comment]
The following seems to work ...at least the last command executed successfully...
```
c:
**mkdir c:\INDY**
git clone https://github.com/kdenhartog/indy-dev.git
**cd    c:\INDY\indy-dev**
docker build -f indy-pool.dockerfile -t indy_pool .
docker build -f indy-dev.dockerfile -t indy_dev .
docker run -itd --net=host -p 127.0.0.1:9701-9708:9701-9708 indy_pool
docker run -it --net=host -p 127.0.0.1:8080:8080 -v **C:\INDY\indy-dev** indy_dev
```

**Comment by mwherman2000** [comment]
While the above executed successfully, I don't think it produced the expected the result ...the mounted folder doesn't appear to be usable...

![image](https://user-images.githubusercontent.com/6101736/50649758-fa663480-0f3b-11e9-939e-acb49bab0979.png)

**Comment by mwherman2000** [comment]
OK ...there's a 2 step solution that makes that the last command work:
1. In the Docker Desktop applet, click Settings, Share Drives, share C: and enter your local Windows 10 login credentials
2. Use an "alias" in the `docker run -v` command:
`    docker run -it --net=host -p 127.0.0.1:8080:8080 -v C:/INDY/indy-dev:/indy-dev2 indy_dev`
In the above, `:/indy-dev2` is the alias. See below.

Screenshot for step 2:
![image](https://user-images.githubusercontent.com/6101736/50651626-318b1480-0f41-11e9-9dfc-3bd7db2e545f.png)

Screenshot for step 1:
![image](https://user-images.githubusercontent.com/6101736/50651672-4d8eb600-0f41-11e9-8f43-a3a623ebf36e.png)

**Comment by kdenhartog** [comment]
Thanks for sharing this. Since I've seen a few issues with windows and versioning, which version of Docker were you using (and do you have a recommended guide to install Docker that I can link to)? 

As a side note, I believe if you use Windows containers instead of Linux containers, the commands that are listed on the Windows guide should work. The main difference between the two are the commands for current directory. Your solution also works, but I prefer not to assume the location of the directory when writing guides. This is why I opted to use the %cd% approach. 

Thanks for publishing the solution here as well. I'll reference this issue for extra details in the Windows section because it offers greater detail into using Docker with windows.

**Comment by kdenhartog** [comment]
Closing this now so it's out of the way of open issues, but remains archived.
