### ISSUE TITLE
add documentation around windows

### ISSUE THREAD

**Issue by kdenhartog** [kdenhartog/indy-dev#5]
add details about working only with windows cmd.exe

**Comment by kdenhartog** [comment]
Still need to add a better environment to get setup through windows. In the meantime, there's now in browser support available.

**Comment by mwherman2000** [comment]
https://github.com/kdenhartog/indy-dev/issues/12 provides some details about the problem (with a solution).

PR https://github.com/kdenhartog/indy-dev/pull/13 documents the solution in an updated version of the README.md

**Comment by kdenhartog** [comment]
Thanks for adding insight into Windows. PR #13 looks good, and I've merged it now. I'm going to close this now, but it will be archived still in the closed issues section.
